Skip to content
Navigation Menu
aliwahab
MikroTikPatchmips

Type / to search
Code
Pull requests
Actions
Projects
Security
Insights
Settings
Files
Go to file
t
.github/workflows
7.1-7.12.1.yml
CustomRos6.yml
CustomRos7.yml
Patchv6.yml
Patchv7.yml
mikrotikv6.yml
netinstallv.yml
x86 V7.yml
toyecc
.gitignore
README.md
latest.txt
latest6.txt
latest7.txt
license.py
mikro.py
npk.py
package.py
patch.py
requirements.txt
sha256.py
MikroTikPatchmips/.github/workflows
/mikrotikv6.yml
 

Code

Blame
72 lines (60 loc) · 2.55 KB
name: MikroTikmipsbe Patch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RouterOS version'
        required: true
        default: '6.49.17'

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
      CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}
      CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
      CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
      CUSTOM_CLOUD_PUBLIC_KEY: ${{ secrets.CUSTOM_CLOUD_PUBLIC_KEY }}
      MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
      MIKRO_NPK_SIGN_PUBLIC_KEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pefile
          sudo apt-get install -y unzip wget
      - name: Run patch script
        run: sudo apt-get install -y mkisofs xorriso qemu-utils extlinux --no-install-recommends
         
      - name: Patch RouterOS main package
        run: |
          wget https://download.mikrotik.com/routeros/$VERSION/routeros-$VERSION-mipsbe.npk
          python3 -E patch.py npk routeros-$VERSION-mipsbe.npk
          mv routeros-$VERSION-mipsbe.npk routeros-$VERSION-mipsbe-patched.npk
          sha256sum routeros-$VERSION-mipsbe-patched.npk > routeros-$VERSION-mipsbe-patched.sha256
      - name: Patch all packages
        run: |
          wget https://download.mikrotik.com/routeros/$VERSION/all_packages-mipsbe-$VERSION.zip
          mkdir ./all_packages-mipsbe
          unzip all_packages-mipsbe-$VERSION.zip -d ./all_packages-mipsbe/
          rm all_packages-mipsbe-$VERSION.zip
          for file in ./all_packages-mipsbe/*.npk; do
            python3 npk.py sign "$file" "$file"
          done
          cd ./all_packages-mipsbe
          zip ../all_packages-mipsbe-$VERSION-patched.zip *.npk
          sha256sum ../all_packages-mipsbe-$VERSION-patched.zip > ../all_packages-mipsbe-$VERSION-patched.sha256
          cd ../
          rm -rf ./all_packages-mipsbe
      - name: Upload patched RouterOS
        uses: actions/upload-artifact@v4
        with:
          name: routeros-patched
          path: |
            routeros-${{ env.VERSION }}-mipsbe-patched.npk
            all_packages-mipsbe-${{ env.VERSION }}-patched.zip
     

           
Footer
© 2025 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact
Manage cookies
Do not share my personal information
