name: Netinstall Patch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RouterOS version'
        required: true
        default: '6.49.17'

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
      CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}
      CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
      CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
      CUSTOM_CLOUD_PUBLIC_KEY: ${{ secrets.CUSTOM_CLOUD_PUBLIC_KEY }}
      MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
      MIKRO_NPK_SIGN_PUBLIC_KEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pefile
          sudo apt-get install -y unzip wget

      - name: Run patch script
        run: sudo apt-get install -y mkisofs xorriso qemu-utils extlinux --no-install-recommends
         
      - name: Patch Netinstall
        run: |
          wget https://download.mikrotik.com/routeros/$VERSION/netinstall-$VERSION.zip
          unzip netinstall-$VERSION.zip
          python3 -E patch.py netinstall netinstall.exe
          zip netinstall-$VERSION-patched.zip netinstall.exe
          sha256sum netinstall-$VERSION-patched.zip > netinstall-$VERSION-patched.sha256
          rm netinstall-$VERSION.zip netinstall.exe LICENSE.txt
     
      - name: Upload patched Netinstall
        uses: actions/upload-artifact@v4
        with:
          name: netinstall-patched
          path: |
            netinstall-${{ env.VERSION }}-patched.zip
            netinstall-${{ env.VERSION }}-patched.sha256

      
